# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20230802-191658-extremal-mackerel

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es

pipeline:
  - name: "SpacyNLP"
    model: "es_core_news_md"
  - name: "SpacyTokenizer"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: "SpacyFeaturizer"
  - name: "DIETClassifier"
    entity_recognition: false  # Añadido para desactivar la extracción de entidades en DIET si se desea
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "SklearnIntentClassifier"

# Configuration for Rasa Core.
policies: 
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 15
    epochs: 100
    constrain_similarities: true
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100

actions:
  - action_guardar_nombre
  - utter_saludo_personalizado