version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: ProyectoChatPaola
    restart: always
    environment:
      MYSQL_DATABASE: 'SafeChatDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ./SafeChatDB.sql:/docker-entrypoint-initdb.d/your_sql_file.sql

volumes:
  mysql: