-- MySQL Script generated by MySQL Workbench
-- Fri Oct 13 13:30:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SafeChatDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SafeChatDB` ;

-- -----------------------------------------------------
-- Schema SafeChatDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SafeChatDB` DEFAULT CHARACTER SET utf8 ;
USE `SafeChatDB` ;

-- -----------------------------------------------------
-- Table `SafeChatDB`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeChatDB`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `SafeChatDB`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `tipoIdentificacion` VARCHAR(45) NOT NULL,
  `numeroIdentificacion` INT(11) NOT NULL,
  `correoElectronico` VARCHAR(45) NULL,
  `numeroCelular` INT(10) NULL,
  `Domicilio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeChatDB`.`TiposDeRecursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeChatDB`.`TiposDeRecursos` ;

CREATE TABLE IF NOT EXISTS `SafeChatDB`.`TiposDeRecursos` (
  `idTiposDeRecursos` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcionTipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTiposDeRecursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeChatDB`.`Recursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeChatDB`.`Recursos` ;

CREATE TABLE IF NOT EXISTS `SafeChatDB`.`Recursos` (
  `idRecursos` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `contacto` VARCHAR(45) NOT NULL,
  `TiposDeRecursos_idTiposDeRecursos` INT NOT NULL,
  PRIMARY KEY (`idRecursos`),
  INDEX `fk_Recursos_TiposDeRecursos1_idx` (`TiposDeRecursos_idTiposDeRecursos` ASC) VISIBLE,
  CONSTRAINT `fk_Recursos_TiposDeRecursos1`
    FOREIGN KEY (`TiposDeRecursos_idTiposDeRecursos`)
    REFERENCES `SafeChatDB`.`TiposDeRecursos` (`idTiposDeRecursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeChatDB`.`TiposDeViolencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeChatDB`.`TiposDeViolencias` ;

CREATE TABLE IF NOT EXISTS `SafeChatDB`.`TiposDeViolencias` (
  `idTiposDeViolencias` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcionTipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTiposDeViolencias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeChatDB`.`Cargos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeChatDB`.`Cargos` ;

CREATE TABLE IF NOT EXISTS `SafeChatDB`.`Cargos` (
  `idCargos` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeChatDB`.`Asesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeChatDB`.`Asesores` ;

CREATE TABLE IF NOT EXISTS `SafeChatDB`.`Asesores` (
  `idAsesores` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `tipoIdentificacion` VARCHAR(45) NOT NULL,
  `numeroIdentificacion` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `Cargos_idCargos` INT NOT NULL,
  PRIMARY KEY (`idAsesores`),
  INDEX `fk_Asesores_Cargos_idx` (`Cargos_idCargos` ASC) VISIBLE,
  CONSTRAINT `fk_Asesores_Cargos`
    FOREIGN KEY (`Cargos_idCargos`)
    REFERENCES `SafeChatDB`.`Cargos` (`idCargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeChatDB`.`Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeChatDB`.`Status` ;

CREATE TABLE IF NOT EXISTS `SafeChatDB`.`Status` (
  `idStatus` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcionStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeChatDB`.`Conversaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeChatDB`.`Conversaciones` ;

CREATE TABLE IF NOT EXISTS `SafeChatDB`.`Conversaciones` (
  `idConversaciones` INT NOT NULL,
  `fechaInicio` DATETIME NULL,
  `fechaFin` DATETIME NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Status_idStatus` INT NOT NULL,
  `Recursos_idRecursos` INT NOT NULL,
  PRIMARY KEY (`idConversaciones`),
  INDEX `fk_Conversaciones_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  INDEX `fk_Conversaciones_Status1_idx` (`Status_idStatus` ASC) VISIBLE,
  INDEX `fk_Conversaciones_Recursos1_idx` (`Recursos_idRecursos` ASC) VISIBLE,
  CONSTRAINT `fk_Conversaciones_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `SafeChatDB`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conversaciones_Status1`
    FOREIGN KEY (`Status_idStatus`)
    REFERENCES `SafeChatDB`.`Status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conversaciones_Recursos1`
    FOREIGN KEY (`Recursos_idRecursos`)
    REFERENCES `SafeChatDB`.`Recursos` (`idRecursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeChatDB`.`Interacciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeChatDB`.`Interacciones` ;

CREATE TABLE IF NOT EXISTS `SafeChatDB`.`Interacciones` (
  `idInteracciones` INT NOT NULL,
  `Conversaciones_idConversaciones` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `TiposDeViolencias_idTiposDeViolencias` INT NOT NULL,
  PRIMARY KEY (`idInteracciones`),
  INDEX `fk_Interacciones_Conversaciones1_idx` (`Conversaciones_idConversaciones` ASC) VISIBLE,
  INDEX `fk_Interacciones_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  INDEX `fk_Interacciones_TiposDeViolencias1_idx` (`TiposDeViolencias_idTiposDeViolencias` ASC) VISIBLE,
  CONSTRAINT `fk_Interacciones_Conversaciones1`
    FOREIGN KEY (`Conversaciones_idConversaciones`)
    REFERENCES `SafeChatDB`.`Conversaciones` (`idConversaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interacciones_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `SafeChatDB`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interacciones_TiposDeViolencias1`
    FOREIGN KEY (`TiposDeViolencias_idTiposDeViolencias`)
    REFERENCES `SafeChatDB`.`TiposDeViolencias` (`idTiposDeViolencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeChatDB`.`Agendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeChatDB`.`Agendas` ;

CREATE TABLE IF NOT EXISTS `SafeChatDB`.`Agendas` (
  `idAgendas` INT NOT NULL,
  `fechaReunion` DATETIME NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Asesores_idAsesores` INT NOT NULL,
  PRIMARY KEY (`idAgendas`),
  INDEX `fk_Agendas_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  INDEX `fk_Agendas_Asesores1_idx` (`Asesores_idAsesores` ASC) VISIBLE,
  CONSTRAINT `fk_Agendas_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `SafeChatDB`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agendas_Asesores1`
    FOREIGN KEY (`Asesores_idAsesores`)
    REFERENCES `SafeChatDB`.`Asesores` (`idAsesores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
